-- REGISTRATION
CREATE TABLE registration(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(89) UNIQUE,
    activation_code VARCHAR(255),
    OTP INT,
    STATUS VARCHAR(89),
    PASSWORD VARCHAR(89),
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    MOBILE NUMERIC,
    IMAGE VARCHAR(400),
    STATE VARCHAR(89),
    CITY VARCHAR(89),
    STREET_ADRS VARCHAR(255),
    LANDMARK VARCHAR(255),
    PIN INT(6)
);
-- NOTIFICATION
CREATE TABLE NOTIFICATION(
    EMAIL VARCHAR(89),
    NOTIFICATION VARCHAR(899),
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--CHECKOUT [SHIPPING ADDRESS]
CREATE TABLE `order_adrs`(
    Order_id INT AUTO_INCREMENT PRIMARY KEY,
    Pay_mode VARCHAR(30),
    Customer_name TEXT,
    MOBILE NUMERIC,
    STATE VARCHAR(89),
    CITY VARCHAR(89),
    STREET_ADRS VARCHAR(255),
    LANDMARK VARCHAR(255),
    PIN INT(6)
);
--CHECKOUT [ORDERED  PRODUCT]
CREATE TABLE `orderd_item`(
    order_id INT,
    Product_name TEXT,
    Quantity INt,
    Price INT,
    Category TEXT,
    SELLER TEXT
)