-- registration
CREATE TABLE registration(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(89) UNIQUE,
    USERNAME VARCHAR(89) UNIQUE,
    PASSWORD VARCHAR(89),
    SELLER_NAME VARCHAR(89),
    MOBILE NUMERIC,
    OTP INT,
    STATUS VARCHAR(89),
    IMAGE VARCHAR(400),
    STREET_ADRS VARCHAR(255),
    LANDMARK VARCHAR(255),
    PIN INT(6)
)